const app = document.querySelector('#app');
const toast = document.querySelector('.toast');
const defaultState = { path:'kids', bestWpm:42, accuracy:96, streak:3, xp:1240, completed:0 };
let state = {...defaultState, ...JSON.parse(localStorage.getItem('dact-furirous-state') || '{}')};
let route = 'home';
const samples = [
  'Le petit renard file sous les étoiles.',
  'Chaque touche devient une nouvelle aventure.',
  'La vitesse arrive quand la précision s’installe.'
];

function save() { localStorage.setItem('dact-furirous-state', JSON.stringify(state)); }
function showToast(message) { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2400); }
function setRoute(next) { route = next; render(); window.scrollTo({top:0, behavior:'smooth'}); }
function button(label, className='button secondary', action='') { return `<button class="${className}" ${action ? `data-action="${action}"` : ''}>${label}</button>`; }

function homeView() {
  const isKids = state.path === 'kids';
  return `<div class="page">
    <section class="hero-grid">
      <div class="race-stage">
        <div class="stage-copy"><p class="eyebrow">Saison 01 · Le départ</p><h1>Prêt à faire<br><span style="color:var(--lime)">vrombir</span> tes doigts ?</h1><p class="lede">Une course courte, un clavier, et c’est parti. Tape juste, tape vite, et transforme chaque mot en turbo.</p>${button('Lancer une course <span>→</span>','button primary','start-race')}</div>
        <div class="track"></div><div class="finish">ARRIVÉE</div><div class="car">🏎️</div>
        <div class="stage-footer"><span>Prochaine piste : <strong>${isKids ? 'Les petites touches' : 'Virage précision'}</strong></span><span>⏱ 60 sec</span></div>
      </div>
      <aside class="command-panel"><div><p class="eyebrow">Ton parcours</p><h2>Choisis ton<br>style de conduite.</h2><div class="path-toggle"><button class="${isKids?'active':''}" data-path="kids">-13 ans</button><button class="${!isKids?'active':''}" data-path="pro">+13 ans</button></div><div class="next-mission"><div class="mission-icon">⚡</div><div><h3>Mission du jour</h3><p>${isKids ? 'Tape 20 mots sans faire de faute.' : 'Garde 95% de précision sur 3 courses.'}</p></div></div></div>${button('Reprendre mon parcours','button secondary','resume')}</aside>
    </section>
    <div class="stats-row"><div class="stat"><span class="stat-label">Meilleure vitesse</span><div class="stat-value">${state.bestWpm}<small>MPM</small></div></div><div class="stat"><span class="stat-label">Précision moyenne</span><div class="stat-value">${state.accuracy}<small>%</small></div></div><div class="stat"><span class="stat-label">Série en cours</span><div class="stat-value">${state.streak}<small>jours 🔥</small></div></div></div>
    <section><div class="section-head"><div><p class="eyebrow">Objectifs actifs</p><h2>Les quêtes du paddock</h2></div>${button('Voir toutes les quêtes →','button ghost','quests')}</div><div class="quest-grid">${quest('🎯','Première ligne','Termine une course avec au moins 90% de précision.',1,1)}${quest('⚡','Coup de boost','Dépasse ta meilleure vitesse personnelle.',3,2)}${quest('🏁','Tour du monde','Découvre 5 circuits différents.',2,5)}</div></section>
  </div>`;
}
function quest(icon,title,desc,current,total) { return `<article class="quest"><div class="quest-icon">${icon}</div><div style="flex:1"><h3>${title}</h3><p>${desc}</p><div class="progress-line"><span style="width:${Math.round(current/total*100)}%"></span></div><div class="quest-meta"><span>${current}/${total}</span><span>+${total*40} XP</span></div></div></article>`; }

function levelsView() { const levels=[['01','Les petites touches','Pose tes doigts et apprends la ligne du milieu.','Débutant','⌨️'],['02','Virage précision','Enchaîne les lettres sans quitter la route.','Débutant','🎯'],['03','Turbo voyelles','Accélère sur les mots les plus courants.','Intermédiaire','⚡'],['04','La grande ligne droite','Phrases et ponctuation à pleine vitesse.','Intermédiaire','🏎️'],['05','Boss final : le texte','Montre tout ce que tu as appris.','Avancé','🏆'],['06','Circuit nocturne','Nouveau circuit bientôt disponible.','Verrouillé','🔒']]; return `<div class="page"><div class="catalog-head"><div><p class="eyebrow">Le paddock</p><h1 style="font-size:48px">Catalogue des circuits</h1><p class="lede">Choisis ta prochaine étape. Chaque circuit travaille un réflexe différent.</p></div><div class="filters"><button class="filter active">Tous</button><button class="filter">-13 ans</button><button class="filter">+13 ans</button></div></div><div class="level-grid">${levels.map((l,i)=>`<article class="level ${i===5?'locked':''}"><div class="level-top"><div><span class="eyebrow">Circuit ${l[0]}</span><h3>${l[1]}</h3></div><span class="level-number">${l[4]}</span></div><div class="level-body"><p>${l[2]}</p><div class="level-meta"><span>${l[3]}</span><span>${i<3?'3 min':'5 min'}</span></div>${i===5?button('Bientôt disponible','button secondary'):button(i===0?'Démarrer':'Voir le circuit','button primary','start-race')}</div></article>`).join('')}</div></div>`; }
function questsView() { return `<div class="page"><p class="eyebrow">Ton garage</p><h1 style="font-size:50px">Chaque tour<br>compte double.</h1><p class="lede">Les quêtes te donnent un objectif clair à chaque session. Pas besoin d’être le plus rapide pour progresser.</p><div class="quest-grid">${quest('🎯','Première ligne','Termine une course avec au moins 90% de précision.',1,1)}${quest('⚡','Coup de boost','Dépasse ta meilleure vitesse personnelle.',3,2)}${quest('🏁','Tour du monde','Découvre 5 circuits différents.',2,5)}${quest('🧠','Mémoire moteur','Tape 3 phrases sans regarder les touches.',0,3)}${quest('🔥','Régulier','Joue 7 jours de suite.',3,7)}${quest('🌟','Pilote propre','Fais une course sans aucune erreur.',0,1)}</div></div>`; }
function profileView() { return `<div class="page"><p class="eyebrow">Pilote</p><h1 style="font-size:50px">Ton tableau<br>de bord.</h1><div class="profile-card"><div class="profile-summary"><span class="avatar">Z</span><div><h2>Zoé</h2><p>Profil local · Parcours ${state.path === 'kids' ? '-13 ans' : '+13 ans'}</p></div></div><div class="stats-row"><div class="stat"><span class="stat-label">XP total</span><div class="stat-value">${state.xp}</div></div><div class="stat"><span class="stat-label">Courses</span><div class="stat-value">${state.completed}</div></div><div class="stat"><span class="stat-label">Niveau</span><div class="stat-value">04</div></div></div></div></div>`; }

function raceView() { return `<div class="race-page"><div class="race-header"><div><p class="eyebrow">Circuit 01 · Les petites touches</p><h1>À toi de jouer.</h1><p>Le premier à la ligne d’arrivée gagne. La précision fait avancer ton bolide.</p></div><div class="timer" id="timer">1:00</div></div><div class="race-board"><div class="race-lanes"><div class="lane"><span class="lane-label">TOI · ${state.path==='kids'?'-13 ANS':'+13 ANS'}</span><div class="lane-progress" id="player-progress"></div><div class="lane-car" id="player-car">🏎️</div></div><div class="lane"><span class="lane-label">RIVALE · PIXEL</span><div class="lane-progress"></div><div class="lane-car">🚙</div></div></div><div class="race-input-area"><label for="type-input">Tape la phrase ci-dessous :</label><div class="text-to-type" id="prompt-text"></div><input class="type-input" id="type-input" autocomplete="off" spellcheck="false" placeholder="Clique ici et commence à taper…" /><div class="race-footer"><span id="race-status">Le chrono démarre à ta première touche.</span><span>Précision <b id="live-accuracy">100%</b></span></div></div></div></div>`; }

function render() { app.innerHTML = route === 'home' ? homeView() : route === 'levels' ? levelsView() : route === 'quests' ? questsView() : route === 'profile' ? profileView() : raceView(); document.querySelectorAll('[data-route]').forEach(el=>el.classList.toggle('active',el.dataset.route===route)); bind(); }
function bind() { document.querySelectorAll('[data-route]').forEach(el=>el.addEventListener('click',()=>setRoute(el.dataset.route))); document.querySelectorAll('[data-action]').forEach(el=>el.addEventListener('click',()=>el.dataset.action==='start-race'?setRoute('race'):el.dataset.action==='quests'?setRoute('quests'):showToast('Parcours repris — à toi de jouer !'))); document.querySelectorAll('[data-path]').forEach(el=>el.addEventListener('click',()=>{state.path=el.dataset.path;save();render();})); if(route==='race') initRace(); }
function initRace() { const input=document.querySelector('#type-input'), prompt=document.querySelector('#prompt-text'), timer=document.querySelector('#timer'); const text=samples[Math.floor(Math.random()*samples.length)]; let started=false, start=0, errors=0, interval; const paint=()=>{ const val=input.value; let html=''; for(let i=0;i<text.length;i++){ const c=text[i]; html += i<val.length ? `<span class="${val[i]===c?'typed':'mistake'}">${c}</span>` : i===val.length?`<span class="current">${c}</span>`:c; } prompt.innerHTML=html; const accuracy=val.length?Math.max(0,Math.round((val.length-errors)/val.length*100)):100; document.querySelector('#live-accuracy').textContent=accuracy+'%'; document.querySelector('#player-progress').style.width=Math.min(100,Math.round(val.length/text.length*100))+'%'; document.querySelector('#player-car').style.left=Math.min(88,Math.round(val.length/text.length*84)+4)+'%'; }; prompt.textContent=text; input.addEventListener('input',()=>{ if(!started){started=true;start=Date.now(); interval=setInterval(()=>{const left=Math.max(0,60-Math.floor((Date.now()-start)/1000)); timer.textContent=`0:${String(left).padStart(2,'0')}`; if(!left){clearInterval(interval);finish(false);} },250); document.querySelector('#race-status').textContent='C’est parti ! Garde le rythme.';} errors=0; [...input.value].forEach((c,i)=>{if(c!==text[i])errors++;}); paint(); if(input.value===text)finish(true); }); function finish(won){clearInterval(interval); input.disabled=true; const elapsed=Math.max(1,(Date.now()-start)/1000); const wpm=Math.round(text.length/5/(elapsed/60)); const acc=Math.max(0,Math.round((text.length-errors)/text.length*100)); state.completed++;state.bestWpm=Math.max(state.bestWpm,wpm);state.accuracy=Math.round((state.accuracy+acc)/2);state.xp+=won?120:40;save(); document.querySelector('.race-input-area').innerHTML=`<div class="result"><p class="eyebrow">${won?'Course gagnée':'Tour terminé'}</p><h2>${won?'Quel pilote ! 🏁':'Bien joué, continue !'}</h2><div class="result-score">${wpm} <small>MPM</small></div><div class="result-stats"><div><strong>${acc}%</strong><span>précision</span></div><div><strong>+${won?120:40}</strong><span>XP gagné</span></div></div>${button('Rejouer','button primary','start-race')} ${button('Retour au paddock','button ghost','home')}</div>`; document.querySelectorAll('[data-action]').forEach(el=>el.addEventListener('click',()=>el.dataset.action==='start-race'?setRoute('race'):setRoute('home'))); } input.focus(); }
render();
